DATABASE_URI='postgresql://<database-url>'

EPICBOX_PORT=443
EPICBOX_DOMAIN="<epicbox-domain>>"
OLD_PROTOCOL_VERSION="1.0.0"
PROTOCOL_VERSION="2.0.0"
LOCAL_PORT=3424
LOCAL_HOST="0.0.0.0"
UPDATE_INTERVAL=20
