DATABASE_URI='postgresql://<database-url>'

OLD_PROTOCOL_VERSION="1.0.0"
PROTOCOL_VERSION="2.0.0"
UPDATE_INTERVAL=20
EPICBOX_DOMAIN="<epicbox-domain>>"
EPICBOX_PORT=443
LOCAL_PORT=3424
LOCAL_HOST="0.0.0.0"
